//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string BLOCKED {
            get {
                return ResourceManager.GetString("BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerificate data not available.
        /// </summary>
        public static string CERTIFICATE_DATA_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("CERTIFICATE_DATA_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate status is not good.
        /// </summary>
        public static string CERTIFICATE_STATUS_IS_NOT_GOOD {
            get {
                return ResourceManager.GetString("CERTIFICATE_STATUS_IS_NOT_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain validation status is not good.
        /// </summary>
        public static string CHAIN_VALIDATION_STATUS_IS_NOT_GOOD {
            get {
                return ResourceManager.GetString("CHAIN_VALIDATION_STATUS_IS_NOT_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims are empty.
        /// </summary>
        public static string CLAIMS_ARE_EMPTY {
            get {
                return ResourceManager.GetString("CLAIMS_ARE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} and {1} do not match.
        /// </summary>
        public static string COMPARE {
            get {
                return ResourceManager.GetString("COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length can be {1}.
        /// </summary>
        public static string CONCRETE_LENGTH {
            get {
                return ResourceManager.GetString("CONCRETE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer does not exist.
        /// </summary>
        public static string CUSTOMER_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CUSTOMER_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is blocked.
        /// </summary>
        public static string CUSTOMER_IS_BLOCKED {
            get {
                return ResourceManager.GetString("CUSTOMER_IS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        public static string DATE_FROM {
            get {
                return ResourceManager.GetString("DATE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        public static string DATE_TO {
            get {
                return ResourceManager.GetString("DATE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number.
        /// </summary>
        public static string DOCUMENT_NUMBER {
            get {
                return ResourceManager.GetString("DOCUMENT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document pin.
        /// </summary>
        public static string DOCUMENT_PİN {
            get {
                return ResourceManager.GetString("DOCUMENT_PİN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document pin is exist.
        /// </summary>
        public static string DOCUMENT_PIN_IS_EXIST {
            get {
                return ResourceManager.GetString("DOCUMENT_PIN_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string GREATER_THAN {
            get {
                return ResourceManager.GetString("GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} greater {1} than or equal to {1}.
        /// </summary>
        public static string GREATERTHANOREQUALTO {
            get {
                return ResourceManager.GetString("GREATERTHANOREQUALTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iamas data is not available.
        /// </summary>
        public static string IAMAS_DATA_IS_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("IAMAS_DATA_IS_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iamas services is not responding.
        /// </summary>
        public static string IAMAS_SERVICES_IS_NOT_RESPONDING {
            get {
                return ResourceManager.GetString("IAMAS_SERVICES_IS_NOT_RESPONDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        public static string INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string INVALID {
            get {
                return ResourceManager.GetString("INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is invalid.
        /// </summary>
        public static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string INVALID_PIN {
            get {
                return ResourceManager.GetString("INVALID_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty.
        /// </summary>
        public static string IS_EMPTY {
            get {
                return ResourceManager.GetString("IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty and must be {1}-{2} range.
        /// </summary>
        public static string IS_EMPTY_OR_UNCORRECT_LENGTH {
            get {
                return ResourceManager.GetString("IS_EMPTY_OR_UNCORRECT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is exist.
        /// </summary>
        public static string IS_EXIST {
            get {
                return ResourceManager.GetString("IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not exist.
        /// </summary>
        public static string IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid.
        /// </summary>
        public static string IS_NOT_VALID {
            get {
                return ResourceManager.GetString("IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string IS_REQUIRED {
            get {
                return ResourceManager.GetString("IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one character must be digit.
        /// </summary>
        public static string ISDIGIT {
            get {
                return ResourceManager.GetString("ISDIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length can be {1}-{2} range.
        /// </summary>
        public static string LENGTH {
            get {
                return ResourceManager.GetString("LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.
        /// </summary>
        public static string LESS_THAN {
            get {
                return ResourceManager.GetString("LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} less than {1} or equal to {1}.
        /// </summary>
        public static string LESSTHANOREQUALTO {
            get {
                return ResourceManager.GetString("LESSTHANOREQUALTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login certificate verification is not good.
        /// </summary>
        public static string LOGIN_CERTIFICATE_VERIFICATION_IS_NOT_GOOD {
            get {
                return ResourceManager.GetString("LOGIN_CERTIFICATE_VERIFICATION_IS_NOT_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one character must be lower case.
        /// </summary>
        public static string LOWERCASE {
            get {
                return ResourceManager.GetString("LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maximum length can be {1}.
        /// </summary>
        public static string MAXIMUMLENGTH {
            get {
                return ResourceManager.GetString("MAXIMUMLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minimum length must be {1}.
        /// </summary>
        public static string MINIMUMLENGTH {
            get {
                return ResourceManager.GetString("MINIMUMLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty.
        /// </summary>
        public static string NOTEMPTY {
            get {
                return ResourceManager.GetString("NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization does not exist.
        /// </summary>
        public static string ORGANIZATION_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("ORGANIZATION_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is blocked.
        /// </summary>
        public static string ORGANIZATION_IS_BLOCKED {
            get {
                return ResourceManager.GetString("ORGANIZATION_IS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name is exist.
        /// </summary>
        public static string ORGANIZATION_NAME_IS_EXIST {
            get {
                return ResourceManager.GetString("ORGANIZATION_NAME_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin is empty.
        /// </summary>
        public static string ORIGIN_IS_EMPTY {
            get {
                return ResourceManager.GetString("ORIGIN_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubOrganization is blocked.
        /// </summary>
        public static string SUB_ORGANIZATION_IS_BLOCKED {
            get {
                return ResourceManager.GetString("SUB_ORGANIZATION_IS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string UNHANDLED_EXCEPTION {
            get {
                return ResourceManager.GetString("UNHANDLED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one characher must be upper case.
        /// </summary>
        public static string UPPERCASE {
            get {
                return ResourceManager.GetString("UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string USER_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is blocked.
        /// </summary>
        public static string USER_IS_BLOCKED {
            get {
                return ResourceManager.GetString("USER_IS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status is not exist.
        /// </summary>
        public static string USER_STATUS_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_STATUS_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voen is not exist.
        /// </summary>
        public static string VOEN_SUN_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("VOEN_SUN_IS_NOT_EXIST", resourceCulture);
            }
        }
    }
}
